NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [236]:
import numpy as np

List vs Numpy - Time Taken

In [237]:
from time import process_time

Time taken by a list

In [238]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.00026100000000006673


In [239]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

4.099999999995774e-05


Numpy Arrays

In [240]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [241]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [242]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [243]:
a.shape

(4,)

In [244]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [245]:
b.shape

(2, 4)

In [246]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [247]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [248]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [249]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [250]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [251]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.89989102 0.99977162 0.70731331 0.64143144]
 [0.7319672  0.92467058 0.14752773 0.31412332]
 [0.90021692 0.70547556 0.47168422 0.1796886 ]]


In [252]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[45 90 88 63 94]
 [54 96 24 48 17]
 [56 95 49 44 87]]


In [253]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [254]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [255]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [256]:
c = np.random.randint(10,90,(5,5))
print(c)

[[51 73 62 57 43]
 [70 61 88 83 21]
 [35 86 49 89 80]
 [15 51 24 52 12]
 [18 53 24 27 14]]


In [257]:
# array dimension
print(c.shape)

(5, 5)


In [258]:
# number of dimensions
print(c.ndim)

2


In [259]:
# number of elements in an array
print(c.size)

25


In [260]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [261]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [262]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [263]:
print(a)
print(b)

[[7 5 4]
 [4 0 7]
 [2 4 8]]
[[15 14 13]
 [19 17 18]
 [11 10 11]]


In [264]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 19 17]
 [23 17 25]
 [13 14 19]]
[[ -8  -9  -9]
 [-15 -17 -11]
 [ -9  -6  -3]]
[[105  70  52]
 [ 76   0 126]
 [ 22  40  88]]
[[0.46666667 0.35714286 0.30769231]
 [0.21052632 0.         0.38888889]
 [0.18181818 0.4        0.72727273]]


In [265]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [266]:
print(a)
print(b)

[[7 4 6]
 [6 0 2]
 [4 0 5]]
[[12 12 16]
 [10 15 15]
 [19 15 19]]


In [267]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 16 22]
 [16 15 17]
 [23 15 24]]
[[ -5  -8 -10]
 [ -4 -15 -13]
 [-15 -15 -14]]
[[84 48 96]
 [60  0 30]
 [76  0 95]]
[[0.58333333 0.33333333 0.375     ]
 [0.6        0.         0.13333333]
 [0.21052632 0.         0.26315789]]


Array Manipulation

In [268]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 1 5]
 [4 9 6]]
(2, 3)


In [269]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 4]
 [1 9]
 [5 6]]
(3, 2)


In [270]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 0 7]
 [5 8 1]]
(2, 3)


In [271]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 5]
 [0 8]
 [7 1]]
(3, 2)


In [272]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 5 4]
 [8 6 0]]
(2, 3)


In [273]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[5 5]
 [4 8]
 [6 0]]
(3, 2)
