# Matrix Problems

In [1]:
import numpy as np


## Creating a Matrix using numpy

In [3]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [6]:
matrix_2.shape

(3, 3)

## Creating Matrices with Random Values

In [7]:
matrix_3 = np.random.rand(3,3)
print(matrix_3)

[[0.23071339 0.17927598 0.46870263]
 [0.29174149 0.36317728 0.5186449 ]
 [0.08916432 0.88003344 0.57049275]]


In [13]:
matrix_4 = np.random.randint(10,100,size=(3,3))# creating matrix with random integers
print(matrix_4)

[[50 65 50]
 [74 63 89]
 [11 37 56]]


## Matrix with all the values as 1

In [17]:
matrix_5 = np.ones((2,3),dtype=int) #dtype to change the datatype
print(matrix_5)

[[1 1 1]
 [1 1 1]]


## Null Matrix or Zero Matrix

In [19]:
matrix_6 = np.zeros((5,5),dtype=int) #dtype to change the datatype
print(matrix_6)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


## Identity Matrix

In [22]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Transpose of a Matrix

In [24]:
# matrix with random integer values
a = np.random.randint(10,100, size=(4,5))
print(a)

[[37 14 65 30 78]
 [71 39 55 58 72]
 [16 76 19 61 89]
 [80 12 66 54 83]]


In [25]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[37 71 16 80]
 [14 39 76 12]
 [65 55 19 66]
 [30 58 61 54]
 [78 72 89 83]]
