# Matrix Problems & Operations

In [50]:
import numpy as np


## Creating a Matrix using numpy

In [51]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [52]:
matrix_1.shape

(2, 2)

In [53]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [54]:
matrix_2.shape

(3, 3)

## Creating Matrices with Random Values

In [55]:
matrix_3 = np.random.rand(3,3)
print(matrix_3)

[[0.95566301 0.16028018 0.7680105 ]
 [0.69960333 0.74913705 0.32725424]
 [0.46982933 0.06460236 0.70083321]]


In [56]:
matrix_4 = np.random.randint(10,100,size=(3,3))# creating matrix with random integers
print(matrix_4)

[[98 71 67]
 [19 45 20]
 [81 58 73]]


## Matrix with all the values as 1

In [57]:
matrix_5 = np.ones((2,3),dtype=int) #dtype to change the datatype
print(matrix_5)

[[1 1 1]
 [1 1 1]]


## Null Matrix or Zero Matrix

In [58]:
matrix_6 = np.zeros((5,5),dtype=int) #dtype to change the datatype
print(matrix_6)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


## Identity Matrix

In [59]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Transpose of a Matrix

In [60]:
# matrix with random integer values
a = np.random.randint(10,100, size=(4,5))
print(a)

[[52 23 42 65 93]
 [91 29 79 32 70]
 [88 62 63 45 75]
 [58 26 88 95 92]]


In [61]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[52 91 88 58]
 [23 29 62 26]
 [42 79 63 88]
 [65 32 45 95]
 [93 70 75 92]]


## Matrix Addition operation

#### Two matrix can be added only if they have the same shape

In [62]:
a = np.array([[3,2],[4,5]])
b = np.array([[2,7],[8,9]])
additioned_matrix = np.add(a,b)
# print(a,'\n',b)
print(additioned_matrix)

[[ 5  9]
 [12 14]]


## Matrix Subtraction operation

In [63]:
a = np.array([[3,2],[4,5]])
b = np.array([[2,7],[8,9]])
subtracted_matrix = np.subtract(a,b)
# print(a,'\n',b)
print(subtracted_matrix)

[[ 1 -5]
 [-4 -4]]


## Matrix Multiplication operation

#### Multiplying a matrix with a scalar

In [68]:
a = np.array([[3,2],[4,5]])
x = 2
multiplied_matrix = np.multiply(x,a)
# print(a,'\n',b)
print(multiplied_matrix)

[[ 6  4]
 [ 8 10]]


In [65]:
a = np.array([[3,2],[4,5]])
b = np.array([[2,7],[8,9]])
multiplied_two_matrix = np.multiply(a,b)
# print(a,'\n',b)
print(multiplied_two_matrix)

[[ 6 14]
 [32 45]]
